---
- name: Install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-enchant
    - php5-mysql
    - python-mysqldb

- name: Disable default pool
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm
